### ISSUE TITLE
자유게시판 API

### ISSUE THREAD

**Issue by chanhong-dev** [SLCommunity/511#25]
## 목적
사용자 전용 자유게시판 구현

## 작업 상세 내용
- [x] 데이터 모델링
- [x] 글 쓰기 API
- [x] 글 삭제 API
- [x] 글 수정 API
- [x] 글 검색 API
- [x] 로그인된 사용자 정보 불러와서 매핑

## 참고사항
ajax 구현 댓글,  front 적용( header, footer ) ,조회수, 정렬 기능 -> 2차 스프린트

**Comment by chanhong-dev** [comment]
로그인된 사용자와 글 쓴 사용자가 같아야 수정 및 삭제를 가능하게 해야할 것 같아요

**Comment by daeun0725** [comment]
ajax 구현,  댓글,  front 적용( header, footer ) ,조회수, 정렬 기능 
 2차 스프린트에 진행하겠습니다
