### ISSUE TITLE
비로그인 사용자 자유게시판 접근 처리

### ISSUE THREAD

**Issue by Ohjinn** [SLCommunity/511#57]
## 목적
시간 되시는분 처리해줄 수 있나요?

## 작업 상세 내용
- [x] 자유게시판 글 저장버튼 누를 때 비 로그인시 아무것도 안뜨는데 글 쓰는 창 들어가기 전에 alert창이 떠서 로그인하라고 이야기 해줘야 할 것 같아요

**Comment by chanhong-dev** [comment]
로그인 필요한 기능에 대한 비로그인 사용자의 접촉을 막는 기능 제가 우선 해볼게요
